"""initial schema users and tasks

Revision ID: cbf3cf87faed
Revises:
Create Date: 2026-09-20 09:01:26.838588
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Imported unconditionally so autogenerated references to custom column
# types resolve; unused imports in revisions are ignored by the linter.
from taskflow.infrastructure.db import types as taskflow_types  # noqa: F401

revision: str = "cbf3cf87faed"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("full_name", sa.String(length=120), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("(true)"), nullable=False),
        sa.Column("created_at", taskflow_types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", taskflow_types.UTCDateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index("uq_users_email", ["email"], unique=True)

    op.create_table(
        "tasks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), server_default="", nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("priority", sa.String(length=10), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("assignee_id", sa.Uuid(), nullable=True),
        sa.Column("due_date", taskflow_types.UTCDateTime(timezone=True), nullable=True),
        sa.Column("completed_at", taskflow_types.UTCDateTime(timezone=True), nullable=True),
        sa.Column("created_at", taskflow_types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", taskflow_types.UTCDateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(status = 'done' AND completed_at IS NOT NULL) OR (status <> 'done' AND completed_at IS NULL)",
            name=op.f("ck_tasks_task_completed_at_consistent"),
        ),
        sa.CheckConstraint(
            "priority IN ('low', 'medium', 'high', 'urgent')",
            name=op.f("ck_tasks_task_priority_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('todo', 'in_progress', 'done', 'cancelled')",
            name=op.f("ck_tasks_task_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["assignee_id"],
            ["users.id"],
            name=op.f("fk_tasks_assignee_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_tasks_owner_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tasks")),
    )
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.create_index(
            "ix_tasks_assignee_id_status", ["assignee_id", "status"], unique=False
        )
        batch_op.create_index("ix_tasks_created_at", ["created_at"], unique=False)
        batch_op.create_index("ix_tasks_due_date", ["due_date"], unique=False)
        batch_op.create_index("ix_tasks_owner_id_status", ["owner_id", "status"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_index("ix_tasks_owner_id_status")
        batch_op.drop_index("ix_tasks_due_date")
        batch_op.drop_index("ix_tasks_created_at")
        batch_op.drop_index("ix_tasks_assignee_id_status")

    op.drop_table("tasks")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index("uq_users_email")

    op.drop_table("users")
    # ### end Alembic commands ###
